baseURL = ""
languageCode = "en-us"
title = "Make It Go"
theme = "tale"
sectionPagesMenu = "main"
[Author]
    name = "B W"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
